import {
  Activity,
  AlertTriangle,
  Archive,
  BarChart3,
  Bell,
  BellRing,
  BookOpen,
  Building2,
  Calculator,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  CalendarPlus,
  CalendarRange,
  CheckCheck,
  ClipboardCheck,
  ClipboardList,
  Contact,
  Database,
  Download,
  Ear,
  FileText,
  FileWarning,
  FolderCheck,
  Forward,
  Gauge,
  Globe,
  History,
  Home,
  Inbox,
  LayoutDashboard,
  LayoutGrid,
  LifeBuoy,
  Lightbulb,
  Lock,
  Megaphone,
  MessageCircle,
  MessageSquare,
  MessagesSquare,
  MessageSquareText,
  NotebookPen,
  PenLine,
  PenSquare,
  Radar,
  ScrollText,
  Send,
  ShieldCheck,
  Sparkles,
  SquarePen,
  Star,
  Table,
  Target,
  Trophy,
  Upload,
  UserCog,
  Users,
  UsersRound,
  type LucideIcon,
} from "lucide-react";

/** Section-level icons — keyed by nav section label (src/lib/nav.ts). */
export const SECTION_ICONS: Record<string, LucideIcon> = {
  Dashboard: LayoutDashboard,
  "Quản lý học sinh": Users,
  "Chuyên cần": CalendarCheck,
  "Giảng dạy & học tập": BookOpen,
  "Giảng dạy bộ môn": BookOpen,
  "Phụ huynh & hoạt động": Megaphone,
  "Tư vấn & an toàn": ShieldCheck,
  "Sổ chủ nhiệm": NotebookPen,
  "Thi đua & năng lực": Trophy,
  "Năng lực giáo viên": Target,
  "Thời khóa biểu & Sổ đầu bài": CalendarRange,
  "Tổ chuyên môn": UsersRound,
  "Giám sát & báo cáo": Radar,
  "Quản trị": Building2,
};

/** Item-level icons — keyed by nav item label. Fallback: SquarePen. */
export const ITEM_ICONS: Record<string, LucideIcon> = {
  // Hồ sơ lớp học
  "Tiếp nhận lớp": Inbox,
  "Upload danh sách học sinh": Upload,
  "Chi tiết hồ sơ học sinh": Contact,
  "Lịch sử cập nhật hồ sơ": History,
  "Báo cáo tổng hợp (AI)": Sparkles,
  // Chuyên cần
  "Điểm danh hàng ngày": CheckCheck,
  "Nghỉ học / đi muộn": CalendarClock,
  "Thông báo phụ huynh": Bell,
  "Theo dõi tình trạng": Activity,
  "Lịch sử chuyên cần": History,
  // Học tập
  "Nhập / đồng bộ điểm": PenSquare,
  "Phân tích kết quả": BarChart3,
  "Học sinh cần hỗ trợ": LifeBuoy,
  "Trao đổi với giáo viên bộ môn": MessageSquare,
  "Trao đổi phụ huynh": MessagesSquare,
  "Trao đổi với giáo viên chủ nhiệm": MessageSquare,
  "Kế hoạch hỗ trợ & tiến bộ": ClipboardList,
  "Quản lý kỳ thi": FileText,
  "Lịch thi": CalendarDays,
  // Rèn luyện
  "Nhận xét & vi phạm/khen thưởng": MessageSquareText,
  "Đánh giá & xếp loại": Star,
  "Trao đổi học sinh": MessageCircle,
  // Tư vấn học sinh
  "Tiếp nhận & phát hiện": Ear,
  "Đánh giá mức độ": Gauge,
  "Chuyển tuyến chuyên gia": Forward,
  // Phụ huynh
  "Soạn & gửi thông báo": Send,
  "Hộp thư phản hồi": Inbox,
  "Lịch hẹn trao đổi": CalendarClock,
  "Cổng thông tin phụ huynh": Globe,
  "Ban đại diện cha mẹ học sinh": UsersRound,
  // Hoạt động giáo dục
  "Lập kế hoạch & phê duyệt": CalendarPlus,
  "Thông báo & đăng ký": Megaphone,
  "Điểm danh & đánh giá": CheckCheck,
  "Duyệt kế hoạch": ClipboardCheck,
  // An toàn học sinh
  "Ghi nhận sự cố": AlertTriangle,
  "Báo cáo Ban Giám Hiệu": FileWarning,
  "Sự cố toàn trường": FileWarning,
  "Theo dõi & nhắc": BellRing,
  "Lưu trữ & tra cứu": Archive,
  // Sổ chủ nhiệm
  "Danh sách học sinh & Tổ": Users,
  "Sơ đồ lớp": LayoutGrid,
  "Lịch sử phiên bản sơ đồ": History,
  "Upload lịch năm học": Upload,
  "Gợi ý công việc (AI)": Lightbulb,
  "Kế hoạch tháng / sơ kết tuần": ClipboardList,
  "Đăng ký chỉ tiêu hiệu suất": Target,
  "Ký duyệt sổ chủ nhiệm": PenLine,
  "Duyệt & khóa sổ học bạ": Lock,
  "Xuất sổ": Download,
  "Nhật ký & lịch sử": ScrollText,
  // Thời khóa biểu & Sổ đầu bài
  "Thời khóa biểu": Table,
  "Sổ đầu bài": NotebookPen,
  // Thi đua
  "Thu thập & tính điểm": Calculator,
  "Xếp hạng & khen thưởng": Trophy,
  // Năng lực giáo viên chủ nhiệm
  "Tự đánh giá & kế hoạch": ClipboardCheck,
  "Minh chứng & đánh giá cuối năm": FolderCheck,
  // Tổ chuyên môn
  "Trang chủ": Home,
  "Danh sách giáo viên": Users,
  "Duyệt đánh giá năng lực": CheckCheck,
  "Sinh hoạt chuyên môn": CalendarDays,
  // Quản trị
  "Dashboard cấp trường": LayoutDashboard,
  "Radar cảnh báo sớm": Radar,
  "Phân công năm học": UserCog,
  "Quản trị người dùng": UserCog,
  "Dashboard cấp Sở Giáo dục và Đào tạo": BarChart3,
  "Quản trị dữ liệu": Database,
  // CR-011 - feature parity
  "Hồ sơ cá nhân": Contact,
  "Tài khoản giáo viên": UserCog,
  "Học sinh toàn trường": Users,
  "Chiến lược & chỉ tiêu": Target,
  "Thiết bị & cơ sở vật chất": Archive,
  "Thông báo toàn trường": Megaphone,
  "Xếp thời khóa biểu": CalendarRange,
  "Sổ đầu bài toàn trường": NotebookPen,
  "Sổ đầu bài phân hiệu": NotebookPen,
  "Phân tích điểm thi": BarChart3,
  "Đơn vị hành chính": Building2,
  "Báo cáo tổng hợp": BarChart3,
  "Cơ sở vật chất": Building2,
  "Dashboard Phòng Giáo dục": BarChart3,
  "Dashboard địa bàn UBND": BarChart3,
  "Nhân sự trường": Users,
  "Cơ sở & đánh giá TT15": Building2,
  "Định mức biên chế Nghị quyết 37": ClipboardList,
};

export const FALLBACK_ICON: LucideIcon = SquarePen;
