import {
  Activity,
  AlertTriangle,
  Archive,
  BarChart3,
  Bell,
  BellRing,
  BookOpen,
  Building2,
  Calculator,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  CalendarPlus,
  CalendarRange,
  CheckCheck,
  ClipboardCheck,
  ClipboardList,
  Contact,
  Database,
  Download,
  Ear,
  FileText,
  FileWarning,
  FolderCheck,
  FolderOpen,
  Forward,
  Gauge,
  Globe,
  HeartHandshake,
  History,
  Home,
  Inbox,
  LayoutDashboard,
  LayoutGrid,
  LifeBuoy,
  Lightbulb,
  Lock,
  Medal,
  Megaphone,
  MessageCircle,
  MessageSquare,
  MessagesSquare,
  MessageSquareText,
  NotebookPen,
  PenLine,
  PenSquare,
  Radar,
  ScrollText,
  Send,
  ShieldCheck,
  Sparkles,
  SquarePen,
  Star,
  Table,
  Target,
  Trophy,
  Upload,
  UserCog,
  Users,
  UsersRound,
  type LucideIcon,
} from "lucide-react";

/** Section-level icons — keyed by nav section label (src/lib/nav.ts). */
export const SECTION_ICONS: Record<string, LucideIcon> = {
  Dashboard: LayoutDashboard,
  "I. Hồ sơ lớp học": FolderOpen,
  "II. Chuyên cần": CalendarCheck,
  "III. Học tập": BookOpen,
  "IV. Rèn luyện": Medal,
  "V. Tư vấn học sinh": HeartHandshake,
  "VI. Phụ huynh": Users,
  "VII. Hoạt động GD": CalendarPlus,
  "VIII. An toàn HS": ShieldCheck,
  "IX. Sổ chủ nhiệm": NotebookPen,
  "X. Thi đua": Trophy,
  "XII. Năng lực GVCN": Target,
  "XIII. Thời khóa biểu & Sổ đầu bài": CalendarRange,
  "Tổ chuyên môn": UsersRound,
  "Quản trị": Building2,
};

/** Item-level icons — keyed by nav item label. Fallback: SquarePen. */
export const ITEM_ICONS: Record<string, LucideIcon> = {
  // I. Hồ sơ lớp học
  "Tiếp nhận lớp": Inbox,
  "Upload danh sách học sinh": Upload,
  "Chi tiết hồ sơ học sinh": Contact,
  "Lịch sử cập nhật hồ sơ": History,
  "Báo cáo tổng hợp (AI)": Sparkles,
  // II. Chuyên cần
  "Điểm danh hàng ngày": CheckCheck,
  "Nghỉ học / đi muộn": CalendarClock,
  "Thông báo phụ huynh": Bell,
  "Theo dõi tình trạng": Activity,
  "Lịch sử chuyên cần": History,
  // III. Học tập
  "Nhập / đồng bộ điểm": PenSquare,
  "Phân tích kết quả": BarChart3,
  "Học sinh cần hỗ trợ": LifeBuoy,
  "Trao đổi với GVBM": MessageSquare,
  "Trao đổi phụ huynh": MessagesSquare,
  "Trao đổi với GVCN": MessageSquare,
  "Kế hoạch hỗ trợ & tiến bộ": ClipboardList,
  "Quản lý kỳ thi": FileText,
  "Lịch thi": CalendarDays,
  // IV. Rèn luyện
  "Nhận xét & vi phạm/khen thưởng": MessageSquareText,
  "Đánh giá & xếp loại": Star,
  "Trao đổi học sinh": MessageCircle,
  // V. Tư vấn học sinh
  "Tiếp nhận & phát hiện": Ear,
  "Đánh giá mức độ": Gauge,
  "Chuyển tuyến chuyên gia": Forward,
  // VI. Phụ huynh
  "Soạn & gửi thông báo": Send,
  "Hộp thư phản hồi": Inbox,
  "Lịch hẹn trao đổi": CalendarClock,
  "Cổng thông tin phụ huynh": Globe,
  "Ban đại diện CMHS": UsersRound,
  // VII. Hoạt động GD
  "Lập kế hoạch & phê duyệt": CalendarPlus,
  "Thông báo & đăng ký": Megaphone,
  "Điểm danh & đánh giá": CheckCheck,
  "Duyệt kế hoạch": ClipboardCheck,
  // VIII. An toàn HS
  "Ghi nhận sự cố": AlertTriangle,
  "Báo cáo BGH": FileWarning,
  "Sự cố toàn trường": FileWarning,
  "Theo dõi & nhắc": BellRing,
  "Lưu trữ & tra cứu": Archive,
  // IX. Sổ chủ nhiệm
  "Danh sách học sinh & Tổ": Users,
  "Sơ đồ lớp": LayoutGrid,
  "Lịch sử phiên bản sơ đồ": History,
  "Upload lịch năm học": Upload,
  "Gợi ý công việc (AI)": Lightbulb,
  "Kế hoạch tháng / sơ kết tuần": ClipboardList,
  "Đăng ký KPI": Target,
  "Ký duyệt sổ chủ nhiệm": PenLine,
  "Duyệt & khóa sổ học bạ": Lock,
  "Xuất sổ": Download,
  "Nhật ký thao tác": ScrollText,
  // XIII. TKB & Sổ đầu bài
  "Thời khóa biểu": Table,
  "Sổ đầu bài": NotebookPen,
  // X. Thi đua
  "Thu thập & tính điểm": Calculator,
  "Xếp hạng & khen thưởng": Trophy,
  // XII. Năng lực GVCN
  "Tự đánh giá & kế hoạch": ClipboardCheck,
  "Minh chứng & đánh giá cuối năm": FolderCheck,
  // Tổ chuyên môn
  "Trang chủ": Home,
  "Danh sách giáo viên": Users,
  "Duyệt đánh giá năng lực": CheckCheck,
  "Sinh hoạt chuyên môn": CalendarDays,
  // Quản trị
  "Dashboard cấp trường": LayoutDashboard,
  "Radar cảnh báo sớm": Radar,
  "Phân công năm học": UserCog,
  "Quản trị người dùng": UserCog,
  "Dashboard cấp Sở GD&ĐT": BarChart3,
  "XI. Quản trị dữ liệu": Database,
};

export const FALLBACK_ICON: LucideIcon = SquarePen;
