// Shared route oracle - single source of truth cho access matrix.
// Spec goc: docs/research/ROLE-MATRIX.md. "admin" duoc danh dau ro o cac
// route implementation cho phep (ky thuat, khong phai vai tro nghiep vu -
// spec: admin gioi han dept/* + school/* read + studio (impl mo studio cho admin
// de debug/demo - documented deviation; activities/parents/safety deny).
export const MATRIX = {
  "/dashboard": ["gvcn"],
  "/attendance/daily": ["gvcn", "bgh"],
  "/attendance/daily-report": ["gvcn"],
  "/attendance/history": ["gvcn", "bgh"],
  "/attendance/leaves": ["gvcn", "bgh"],
  "/attendance/notify": ["gvcn", "bgh"],
  "/attendance/tracking": ["gvcn", "bgh"],
  "/academics/grades": ["gvcn", "gvbm", "to_truong", "bgh"],
  "/academics/exams": ["gvcn", "gvbm", "to_truong", "bgh"],
  "/academics/lesson-plans": ["gvcn", "gvbm"],
  "/academics/analysis": ["gvcn", "bgh"],
  "/academics/parent-chat": ["gvcn"],
  "/academics/plans": ["gvcn", "bgh"],
  "/academics/support": ["gvcn", "bgh"],
  "/academics/teacher-chat": ["gvcn", "gvbm", "to_truong"],
  "/schedule/timetable": ["gvcn", "gvbm", "to_truong", "bgh", "pht"],
  "/schedule/period-log": ["gvcn", "gvbm", "to_truong"],
  "/schedule/manage": ["bgh", "pht"],
  "/conduct/evaluation": ["gvcn", "bgh"],
  "/conduct/records": ["gvcn", "bgh"],
  "/conduct/student-chat": ["gvcn", "bgh"],
  "/counseling/intake": ["gvcn", "bgh"],
  "/counseling/assessment": ["gvcn", "bgh"],
  "/counseling/referral": ["gvcn", "bgh"],
  "/activities/plan": ["gvcn", "bgh"],
  "/activities/attendance": ["gvcn", "bgh"],
  "/activities/announce": ["gvcn", "bgh"],
  "/emulation/scoring": ["gvcn", "bgh"],
  "/emulation/ranking": ["gvcn", "bgh"],
  "/parents/compose": ["gvcn", "bgh"],
  "/parents/inbox": ["gvcn", "bgh"],
  "/parents/appointments": ["gvcn", "bgh"],
  "/parents/cmhs": ["gvcn", "bgh"],
  "/parents/portal": ["gvcn", "bgh"],
  "/records/students": ["gvcn", "bgh"],
  "/records/upload": ["gvcn", "bgh"],
  "/records/intake": ["gvcn", "bgh"],
  "/records/report": ["gvcn", "bgh"],
  "/records/history": ["gvcn", "bgh"],
  "/register/roster": ["gvcn"],
  "/register/seating": ["gvcn"],
  "/register/seating-history": ["gvcn"],
  "/register/kpi": ["gvcn"],
  "/register/plans": ["gvcn"],
  "/register/suggestions": ["gvcn"],
  "/register/export": ["gvcn"],
  "/register/signoff": ["gvcn", "bgh"],
  "/register/lock-records": ["gvcn", "bgh"],
  "/register/audit": ["gvcn", "bgh"],
  "/register/year-events": ["gvcn"],
  "/competency/evidence": ["gvcn", "gvbm", "to_truong"],
  "/competency/self-assessment": ["gvcn", "gvbm", "to_truong"],
  "/safety/report": ["gvcn", "gvbm", "to_truong", "bgh"],
  "/safety/bgh": ["bgh", "pht"],
  "/safety/followup": ["gvcn", "bgh"],
  "/safety/archive": ["gvcn", "bgh"],
  "/school/dashboard": ["bgh", "pht", "admin"],
  "/school/staff": ["bgh", "pht", "ke_toan"],
  "/school/users": ["bgh", "admin"],
  "/school/students": ["bgh", "admin"],
  "/school/announce": ["bgh", "pht"],
  "/school/approvals": ["bgh", "pht"],
  "/school/assignments": ["bgh"],
  "/school/campuses": ["bgh", "pht", "ke_toan"],
  "/school/daily-reports": ["bgh", "pht"],
  "/school/equipment": ["bgh", "pht", "ke_toan"],
  "/school/exam-analytics": ["bgh", "pht"],
  "/school/journals": ["bgh", "pht"],
  "/school/nq37": ["bgh", "pht", "ke_toan"],
  "/school/radar": ["bgh", "pht", "admin"],
  "/school/strategy": ["bgh", "pht"],
  "/school/substitutes": ["bgh", "pht"],
  "/school/ai-assistant": ["bgh", "pht"],
  "/team/home": ["to_truong"],
  "/team/lesson-plans": ["to_truong"],
  "/team/meetings": ["to_truong"],
  "/team/review": ["to_truong"],
  "/team/teachers": ["to_truong"],
  "/dept/dashboard": ["so_gd", "ubnd", "admin"],
  "/dept/data": ["so_gd", "admin"],
  "/dept/facilities": ["so_gd", "ubnd", "admin"],
  "/dept/reports": ["so_gd", "ubnd", "admin"],
  "/dept/users": ["so_gd", "admin"],
  "/dept/wards": ["so_gd", "ubnd", "admin"],
  "/dept/schools": ["so_gd", "admin"],
  "/dept/usage": ["so_gd", "admin"],
  "/studio": ["gvcn", "gvbm", "to_truong", "bgh", "admin"],
  "/studio/library": ["gvcn", "gvbm", "to_truong", "bgh", "admin"],
  "/studio/literature": ["gvcn", "gvbm", "to_truong", "bgh", "admin"],
  "/studio/mau-khbd": ["gvcn", "gvbm", "to_truong", "bgh", "admin"],
  "/studio/questions": ["gvcn", "gvbm", "to_truong", "bgh", "admin"],
  "/studio/yccd": ["gvcn", "gvbm", "to_truong", "bgh", "admin"],
  "/portal/parent": ["phu_huynh"],
  "/portal/student": ["hoc_sinh"],
  "/portal/student/hoc-ba": ["hoc_sinh"],
  "/profile": ["gvcn", "gvbm", "to_truong", "bgh", "pht", "ke_toan", "so_gd", "ubnd", "admin"],
  "/notifications": ["gvcn", "gvbm", "to_truong", "bgh", "pht", "ke_toan", "so_gd", "ubnd", "admin"],
};

// Route alias hop le (redirect duoc cho phep)
export const ALIASES = { "/records/history": "/register/audit" };

export const ROLE_EMAIL = {
  gvcn: "anhptl@nd.scn", gvbm: "minhtv@nd.scn", to_truong: "hanhlth@nd.scn",
  bgh: "hainv@nd.scn", pht: "duclm@nd.scn", ke_toan: "trangpt@nd.scn",
  so_gd: "sovqt@demo.scn", ubnd: "daonvl@demo.scn", admin: "admin@demo.scn",
  phu_huynh: "annv@nd.scn", hoc_sinh: "baong@nd.scn",
};

export const ROLE_HOME = {
  gvcn: "/dashboard", gvbm: "/academics/grades", to_truong: "/team/home",
  bgh: "/school/dashboard", pht: "/school/dashboard", ke_toan: "/school/staff",
  so_gd: "/dept/dashboard", ubnd: "/dept/dashboard", admin: "/dept/dashboard",
  phu_huynh: "/portal/parent", hoc_sinh: "/portal/student",
};
